import { Capture, Template } from 'aws-cdk-lib/assertions';
import * as cdk from 'aws-cdk-lib';

import { CompetitionsStack } from '../competitions.stack';

/**
 * Unit test
 *
 * Tests the CloudFormation template generated by the CDK
 */

describe('CompetitionsStack', () => {
  let app: cdk.App;
  let stack: CompetitionsStack;
  let template: Template;

  beforeAll(() => {
    app = new cdk.App();
    stack = new CompetitionsStack(app, 'CompetitionsStack');
    template = Template.fromStack(stack);
  });

  describe('Should contain a lambda for creating competitions', () => {
    const layers = new Capture();

    it('Should exist', () => {
      template.hasResourceProperties('AWS::Lambda::Function', {
        FunctionName: 'AudioUeCreateCompetitionLambda',
        Layers: layers,
      });
    });

    it('Should have 3 layers attached', () => {
      expect(layers.asArray()).toHaveLength(3);
    });

    // TODO: additional tests for the lambda
  });
});
