get:
  summary: Accept incoming events from external systems in relation to courses
  parameters:
    - name: sourceKey
      in: path
      required: true
      schema:
        type: string
      description: The identifier for the SOURCE this sourceId is coming from. i.e. COURSE, AUTH, CRM, etc
    - name: courseSourceEvent
      in: path
      required: true
      schema:
        type: string
        enum: [created, updated, status-updated]
      description: >
        The event that has occurred to this item
          * `created` - When a course has been created
          * `updated` - When a course has been updated
          * `status-updated` - A course has changed status; similar to updated, but more specific
    - name: courseSourceId
      in: path
      required: true
      schema:
        type: string
      description: The identifier for the specific course from this source.
    - name: updatedStatus
      in: query
      required: false
      schema:
        type: string
      description: The updated status; only relevant for `status-updated` events

  responses:
    '200':
      description: Event processed successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    '400':
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: "../../domain/entities/error.yaml"

    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "../../domain/entities/error.yaml"
