import { Capture, Template } from 'aws-cdk-lib/assertions';
import * as cdk from 'aws-cdk-lib';

import { MembersStack } from '../members.stack';

/**
 * Unit test
 *
 * Tests the CloudFormation template generated by the CDK
 */

describe('MembersStack', () => {
  let app: cdk.App;
  let stack: MembersStack;
  let template: Template;

  beforeAll(() => {
    app = new cdk.App();
    stack = new MembersStack(app, 'MembersStack');
    template = Template.fromStack(stack);
  });

  describe('Should contain a lambda for creating members', () => {
    const layers = new Capture();

    it('Should exist', () => {
      template.hasResourceProperties('AWS::Lambda::Function', {
        FunctionName: 'CcMembersMemberCreateLambda',
        Layers: layers,
      });
    });

    it('Should have 3 layers attached', () => {
      expect(layers.asArray()).toHaveLength(3);
    });

    // TODO: additional tests for the lambda
    // TODO: test RE subscribed to event with the correct rule details
  });

  describe('Should contain a lambda for updating members', () => {
    const layers = new Capture();

    it('Should exist', () => {
      template.hasResourceProperties('AWS::Lambda::Function', {
        FunctionName: 'CcMembersMemberUpdateLambda',
        Layers: layers,
      });
    });

    it('Should have 3 layers attached', () => {
      expect(layers.asArray()).toHaveLength(3);
    });

    // TODO: additional tests for the lambda
    // TODO: test RE subscribed to event with the correct rule details
  });

  describe('Should contain a lambda for creating participants', () => {
    const layers = new Capture();

    it('Should exist', () => {
      template.hasResourceProperties('AWS::Lambda::Function', {
        FunctionName: 'CcMembersParticipantCreateLambda',
        Layers: layers,
      });
    });

    it('Should have 3 layers attached', () => {
      expect(layers.asArray()).toHaveLength(3);
    });

    // TODO: additional tests for the lambda
    // TODO: test RE subscribed to event with the correct rule details
  });

  describe('Should contain a lambda for updating participants', () => {
    const layers = new Capture();

    it('Should exist', () => {
      template.hasResourceProperties('AWS::Lambda::Function', {
        FunctionName: 'CcMembersParticipantUpdateLambda',
        Layers: layers,
      });
    });

    it('Should have 3 layers attached', () => {
      expect(layers.asArray()).toHaveLength(3);
    });

    // TODO: additional tests for the lambda
    // TODO: test RE subscribed to event with the correct rule details
  });
});
