openapi: "3.1.0"
info:
  version: 1.0.0
  title: Curious Communities admin API
  description: These are the admin API endpoints for the Curious Communities system.
servers:
  - url: http://to.be.defined/v1

paths:

  # Hooks
  # External events

  # Course
  /hook/external-event/course/{sourceKey}/{courseSourceEvent}/{courseSourceId}?{updatedStatus?}:
    $ref: "./src/infra/hook-course/hook.path.yaml"

  # Participant
  /hook/external-event/participant/{sourceKey}/{participantSourceEvent}/{participantSourceId}?{updatedStatus?}:
    $ref: "./src/infra/hook-participant/hook.path.yaml"
