name: Build and test

# UP TO
# tests fail due to ../../../../dist/local/@curioushuman/cdk-utils/src
# will need to package it up and install it from npm (or similar)

# ALSO
# CDK won't work for similar reasons, so have pulled the pin on beta for now
# https://towardsthecloud.com/aws-cdk-openid-connect-github

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    # - name: Run unit tests
    #   run: pnpm run test
